In [1]:
import numpy as np
import pandas as pd 

### To read the file
data = pd.read_csv(r'C:\Users\Kavya\OneDrive\Documents\Data sets\auto-mpg.csv')

In [3]:
data

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [4]:
data['mpg'].values

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [5]:
# Find mean
data['mpg'].mean()


np.float64(23.514572864321607)

In [6]:
# Find median
data['mpg'].median()

np.float64(23.0)

In [7]:
# Find SD
data['mpg'].std()

np.float64(7.815984312565782)

In [8]:
#  cars with mpg greater than 25. 
data[data['mpg']>25]

mpg  cylinders  displacement horsepower  weight  acceleration  \
18   27.0          4          97.0         88    2130          14.5   
19   26.0          4          97.0         46    1835          20.5   
23   26.0          4         121.0        113    2234          12.5   
29   27.0          4          97.0         88    2130          14.5   
30   28.0          4         140.0         90    2264          15.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                      car name  
18           70       3                  datsun pl510  
19           70       2  volkswagen 1131 deluxe sedan  
23           70       2                      bmw 2002  
29           71       3                  datsun pl510  
30           71       1           chevrolet vega 2300  
..          ...     ...                           ...  
393          82       1               ford mustang gl  
394          82       2                     vw pickup  
395          82       1                 dodge rampage  
396          82       1                   ford ranger  
397          82       1                    chevy s-10  

[158 rows x 9 columns]

In [9]:
# cars with more than 6 cylinders. 
data[data['cylinders']>6]

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
291  19.2          8         267.0        125    3605          15.0   
292  18.5          8         360.0        150    3940          13.0   
298  23.0          8         350.0        125    3900          17.4   
300  23.9          8         260.0         90    3420          22.2   
364  26.6          8         350.0        105    3725          19.0   

     model year  origin                              car name  
0            70       1             chevrolet chevelle malibu  
1            70       1                     buick skylark 320  
2            70       1                    plymouth satellite  
3            70       1                         amc rebel sst  
4            70       1                           ford torino  
..          ...     ...                                   ...  
291          79       1         chevrolet malibu classic (sw)  
292          79       1  chrysler lebaron town @ country (sw)  
298          79       1                     cadillac eldorado  
300          79       1     oldsmobile cutlass salon brougham  
364          81       1                 oldsmobile cutlass ls  

[103 rows x 9 columns]

In [10]:
# corresponding car_name
data[data['cylinders']>6]['car name']

0                 chevrolet chevelle malibu
1                         buick skylark 320
2                        plymouth satellite
3                             amc rebel sst
4                               ford torino
                       ...                 
291           chevrolet malibu classic (sw)
292    chrysler lebaron town @ country (sw)
298                       cadillac eldorado
300       oldsmobile cutlass salon brougham
364                   oldsmobile cutlass ls
Name: car name, Length: 103, dtype: object

In [11]:
# 25th, 50th, and 75th percentiles of the weight column 
x = np.percentile(data['weight'],25)
y = np.percentile(data['weight'],50)
z = np.percentile(data['weight'],75)
print(x,y,z)

2223.75 2803.5 3608.0


In [12]:
a = data['acceleration'].values
print(a)

# normalize acceleration values (scale between 0 and 1). 
normalizedData = (a-np.min(a))/(np.max(a)-np.min(a))
print(normalizedData)

[12.  11.5 11.  12.  10.5 10.   9.   8.5 10.   8.5 10.   8.   9.5 10.
 15.  15.5 15.5 16.  14.5 20.5 17.5 14.5 17.5 12.5 15.  14.  15.  13.5
 18.5 14.5 15.5 14.  19.  13.  15.5 15.5 15.5 15.5 12.  11.5 13.5 13.
 11.5 12.  12.  13.5 19.  15.  14.5 14.  14.  19.5 14.5 19.  18.  19.
 20.5 15.5 17.  23.5 19.5 16.5 12.  12.  13.5 13.  11.5 11.  13.5 13.5
 12.5 13.5 12.5 14.  16.  14.  14.5 18.  19.5 18.  16.  17.  14.5 15.
 16.5 13.  11.5 13.  14.5 12.5 11.5 12.  13.  14.5 11.  11.  11.  16.5
 18.  16.  16.5 16.  21.  14.  12.5 13.  12.5 15.  19.  19.5 16.5 13.5
 18.5 14.  15.5 13.   9.5 19.5 15.5 14.  15.5 11.  14.  13.5 11.  16.5
 17.  16.  17.  19.  16.5 21.  17.  17.  18.  16.5 14.  14.5 13.5 16.
 15.5 16.5 15.5 14.5 16.5 19.  14.5 15.5 14.  15.  15.5 16.  16.  16.
 21.  19.5 11.5 14.  14.5 13.5 21.  18.5 19.  19.  15.  13.5 12.  16.
 17.  16.  18.5 13.5 16.5 17.  14.5 14.  17.  15.  17.  14.5 13.5 17.5
 15.5 16.9 14.9 17.7 15.3 13.  13.  13.9 12.8 15.4 14.5 17.6 17.6 22.2
 22.1 14.2 17

In [13]:
# check for null values
data['horsepower'].isna()

0      False
1      False
2      False
3      False
4      False
       ...  
393    False
394    False
395    False
396    False
397    False
Name: horsepower, Length: 398, dtype: bool

In [14]:
# Check data type of columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [15]:
# Convert ? to zero and convert horse power field to float and find its mean

power = data['horsepower'].to_numpy()
hp = np.where(power == '?', '0', power)
data['horsepower'] = hp.astype(float)
m = np.mean(data['horsepower'])
print(m)

102.89447236180905


In [16]:
# Replace zero by mean
#data[data['horsepower'] == '0'] = m
horse_power = np.where(data['horsepower'] == '0', m, data['horsepower'])

In [17]:
# Create new column with new values

data['new_horsepower'] = data['horsepower'] + (0.1 * data['horsepower'])

In [18]:
data

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  new_horsepower  
0            70       1  chevrolet chevelle malibu           143.0  
1            70       1          buick skylark 320           181.5  
2            70       1         plymouth satellite           165.0  
3            70       1              amc rebel sst           165.0  
4            70       1                ford torino           154.0  
..          ...     ...                        ...             ...  
393          82       1            ford mustang gl            94.6  
394          82       2                  vw pickup            57.2  
395          82       1              dodge rampage            92.4  
396          82       1                ford ranger            86.9  
397          82       1                 chevy s-10            90.2  

[398 rows x 10 columns]

In [19]:
# Find the average displacement of cars with an origin of 2
boolean_mask = data['origin'] == 2
r = data['displacement'][boolean_mask]
print(r)
avg = np.mean(r)
print(avg)

19      97.0
20     110.0
21     107.0
22     104.0
23     121.0
       ...  
354    100.0
359    141.0
360    145.0
375    105.0
394     97.0
Name: displacement, Length: 70, dtype: float64
109.14285714285714


In [20]:
# Create a new array
new_array = data[['mpg','horsepower', 'weight']]
new_arr = new_array.values
print(new_arr)

[[  18.  130. 3504.]
 [  15.  165. 3693.]
 [  18.  150. 3436.]
 ...
 [  32.   84. 2295.]
 [  28.   79. 2625.]
 [  31.   82. 2720.]]


In [21]:
# Find dot product
for i in new_arr:
 vector_a = np.array([1, 0.5, -0.2])
vector_b = i
dot_product = np.dot(vector_a, vector_b)
print(dot_product)

-472.00000000000006


In [22]:
# To sort in descending order
arr2 = data.values
#print(arr2)
sorted = arr2[arr2[:, 6].argsort()[::-1]]
print(sorted)

[[31.0 4 119.0 ... 1 'chevy s-10' 90.2]
 [36.0 4 107.0 ... 3 'honda accord' 82.5]
 [28.0 4 120.0 ... 1 'ford ranger' 86.9]
 ...
 [11.0 8 318.0 ... 1 'dodge d200' 231.0]
 [9.0 8 304.0 ... 1 'hi 1200d' 212.3]
 [18.0 8 307.0 ... 1 'chevrolet chevelle malibu' 143.0]]


In [23]:
# Get first 5 car names
#p =np.delete(sorted, slice(0, 6), axis = 0)
car_name = sorted[:5]
print(car_name[:,8])

['chevy s-10' 'honda accord' 'ford ranger' 'chevrolet cavalier'
 'chevrolet cavalier wagon']


In [24]:
# Find correlation coefficient
correlation_coefficient = np.corrcoef(data['mpg'], data['weight'])[0, 1]
print(correlation_coefficient)

-0.8317409332443352


In [26]:
# Group by the cylinders and calculate the mean of mpg
#unique_cylinders = np.unique(data[:, 1])  # Get unique 
#cylinders = data['cylinders'].to_numpy()
#mpg = data['mpg'].to_numpy()
#grouped_means = []
#for cylinders in unique_cylinders:
    #cylinder_data = data[data[:, 1] == cylinders]
    #mean_mpg = np.mean(mpg[:, 0].astype(float))
    #grouped_means.append([mpg, mean_mpg])

# Convert the result to a NumPy array
#grouped_means = np.array(grouped_means)

# Print the result
#print(grouped_means)